### ISSUE TITLE
RMX2200 OTA_0180

### ISSUE THREAD

**Issue by google-mirror** [RealmeUpdater/realme-updates-tracker#7]
RMX2200_11_OTA_0180_all_V9mQgsLHct5n.ozip
https://ota-manual-cn.allawnfs.com/ota/21/04/23/a5b626c1-049f-4874-adb9-4dbab28f6508.ozip

RMX2200_11_OTA_0170-0180_patch_V9mQgsLHct5n.ozip
https://ota-manual-cn.allawnfs.com/ota/21/04/23/ecdac8c0-10a6-422b-b864-e7b3e31243b9.ozip

**Comment by yshalsager** [comment]
Availabe here now https://realmeupdater.com/downloads/archive/RMX2200/
